<a href="https://colab.research.google.com/github/KalaiselviNarendar/Machine-Learning/blob/main/Linear_regression_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_boston
boston_bunch=load_boston()
print(type(boston_bunch))

<class 'sklearn.utils.Bunch'>


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
print(boston_bunch.data)
print(boston_bunch.feature_names)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [ ]:
import pandas as pd
boston_df=pd.DataFrame(data=boston_bunch.data,columns=boston_bunch.feature_names)
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [ ]:
boston_df.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [ ]:
boston_df.shape

(506, 13)

In [ ]:
boston_df['MEDV']=boston_bunch.target
boston_df.shape

(506, 14)

In [ ]:
y=boston_df['MEDV']
y.shape
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [ ]:
x=boston_df.drop('MEDV',axis=1)
x.shape

(506, 13)

In [ ]:
from pandas.core.common import random_state
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=21)
print("shape of x train is: ",x_train.shape)
print("shape of x test is: ",x_test.shape)
print("shape of y train is: ",y_train.shape)
print("shape of y test is: ",y_test.shape)

shape of x train is:  (404, 13)
shape of x test is:  (102, 13)
shape of y train is:  (404,)
shape of y test is:  (102,)


In [ ]:
from sklearn import model_selection
#Building ML
from sklearn.linear_model import LinearRegression
model_lr=LinearRegression()
model_lr.fit(x_train,y_train)
print(model_lr.coef_)
print(model_lr.intercept_)
y_test_pred=model_lr.predict(x_test)


[-8.77422649e-02  4.87770336e-02  1.94746142e-02  3.06314365e+00
 -1.84821160e+01  3.34704170e+00  3.22024333e-03 -1.42569490e+00
  3.25184188e-01 -1.20259158e-02 -1.05582832e+00  1.07682087e-02
 -5.38356500e-01]
40.653176529790805


In [ ]:
pd.DataFrame({'Actual values':y_test,'Predicted values':y_test_pred}).head(20)

In [ ]:
model_lr.score(x_test,y_test)

0.714936416139222

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np
print(np.sqrt(mean_squared_error(y_test,y_test_pred)))

5.179324335658013


In [ ]:
y_train_pred=model_lr.predict(x_train)
print(np.sqrt(mean_squared_error(y_train,y_train_pred)))

4.56559560944838


In [ ]:
boston_df.corr()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
ZN      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
INDUS    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
CHAS    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
NOX      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
RM      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
AGE      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
DIS     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
RAD      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
TAX      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
PTRATIO  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
B       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
LSTAT    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
MEDV    -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              DIS       RAD       TAX   PTRATIO         B     LSTAT      MEDV  
CRIM    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
RM       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
MEDV     0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

In [ ]:
# RAD and TX have strong + ve correlation 9...
#age and dis, dis and nox
#indus and nox,age and nox, indus and tax =>strong + ve correlation
#indus and dis col => -7.80...
#how to decide which col to drop
#cols correlation with other col
# indus is haveing with other col
# adn dis but now removing only indus
# so we need to revist the describe information of the dataset so we can come to conclusion
#based on the corr analysis and feature information we deicide to drop INDUS,age and rad columns

In [ ]:
correlated_cols=['INDUS','AGE','RAD']
boston_df_new=boston_df.drop(correlated_cols,axis=1)
boston_df_new.head()

CRIM    ZN  CHAS    NOX     RM     DIS    TAX  PTRATIO       B  LSTAT  \
0  0.00632  18.0   0.0  0.538  6.575  4.0900  296.0     15.3  396.90   4.98   
1  0.02731   0.0   0.0  0.469  6.421  4.9671  242.0     17.8  396.90   9.14   
2  0.02729   0.0   0.0  0.469  7.185  4.9671  242.0     17.8  392.83   4.03   
3  0.03237   0.0   0.0  0.458  6.998  6.0622  222.0     18.7  394.63   2.94   
4  0.06905   0.0   0.0  0.458  7.147  6.0622  222.0     18.7  396.90   5.33   

   MEDV  
0  24.0  
1  21.6  
2  34.7  
3  33.4  
4  36.2

In [ ]:
x_new=boston_df_new.drop('MEDV',axis=1)
y_new=boston_df_new['MEDV']

In [ ]:
x_train_new,x_test_new,y_train_new,y_test_new=train_test_split(x_new,y_new,test_size=0.2,random_state=21)

In [ ]:
model_lr_new=LinearRegression()
model_lr_new.fit(x_train_new,y_train_new)
print(model_lr_new.coef_)
print(model_lr_new.intercept_)


[-2.59160041e-02  4.52635230e-02  3.48354385e+00 -1.71848736e+01
  3.66677572e+00 -1.40462069e+00  1.32452378e-03 -9.40703052e-01
  1.00473210e-02 -5.37794179e-01]
33.85014194417384


In [ ]:
y_train_new_pred=model_lr_new.predict(x_train_new)
y_test_new_pred=model_lr_new.predict(x_test_new)
pd.DataFrame({'Actual values':y_test_new,'Predicted values':y_test_new_pred}).head(20)

Actual values  Predicted values
455           14.1         14.619833
142           13.4         16.504425
311           22.1         27.085959
232           41.7         36.888321
290           28.5         32.837995
20            13.6         12.792521
347           23.1         26.377420
219           23.0         29.770477
57            31.6         32.570464
61            16.0         17.368368
35            18.9         23.398238
397            8.5         15.637522
239           23.3         28.052887
415            7.2          9.258709
442           18.4         17.907731
52            25.0         27.223712
450           13.4         15.410539
173           23.6         28.780908
141           14.4          5.584505
316           17.8         17.723558

In [ ]:
model_lr_new.score(x_test_new,y_test_new)

0.7076907132019576

In [ ]:
print(np.sqrt(mean_squared_error(y_test_new,y_test_new_pred)))
print(np.sqrt(mean_squared_error(y_train_new,y_train_new_pred)))

5.244734934861608
4.689368250003447


In [ ]:
# Rsquare is high in model without removing correlated value so taking that for further calculation

In [ ]:
#Ridge Algorithm

In [ ]:
from sklearn.linear_model import Ridge
ridge_reg_model=Ridge(alpha=0.001)
ridge_reg_model.fit(x_train,y_train)
y_test_pred_ridge=ridge_reg_model.predict(x_test)
y_train_pred_ridge=ridge_reg_model.predict(x_train)
ridge_reg_model.score(x_test,y_test)

0.7149402374816218

In [ ]:
np.sqrt(mean_squared_error(y_test,y_test_pred_ridge))

5.17928962052929

In [ ]:
np.sqrt(mean_squared_error(y_train,y_train_pred_ridge))

4.565595683032424

In [ ]:
#Lasso Algorithm

In [ ]:
from sklearn.linear_model import Lasso
lasso_reg_model=Lasso(alpha=0.02)
lasso_reg_model.fit(x_train,y_train)
y_test_pred_lasso=lasso_reg_model.predict(x_test)
y_train_pred_lasso=lasso_reg_model.predict(x_train)
lasso_reg_model.score(x_test,y_test)


0.7152387876779756

In [ ]:
#np.sqrt(mean_squared_error(y_test,y_test_pred_lasso))
np.sqrt(mean_squared_error(y_test,y_test_pred_lasso))

5.17657671044418

In [ ]:
np.sqrt(mean_squared_error(y_train,y_train_pred_lasso))

4.580819309496862

In [ ]:
#Elasticnet

In [ ]:
from sklearn.linear_model import ElasticNet
elasticnet_model=ElasticNet(alpha=0.003)
elasticnet_model.fit(x_train,y_train)
y_test_pred_elastic=elasticnet_model.predict(x_test)
y_train_pred_elastic=elasticnet_model.predict(x_train)
elasticnet_model.score(x_test,y_test)

0.7153431806529481

In [ ]:
np.sqrt(mean_squared_error(y_test,y_test_pred_elastic))

5.175627761366953

In [ ]:
np.sqrt(mean_squared_error(y_train,y_train_pred_elastic))

4.579346111143414